# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-pdf

custom:
  bucket: simeonhtml2pdf

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - s3:PutObject
  #     Resource: "arn:aws:s3:::${self:custom.bucket}/*"

# The `functions` block defines what code to deploy
functions:
  html:
    handler: handler.handler
    environment:
      BUCKET: ${self:custom.bucket}
    # The `events` block defines how to trigger the handler.handler code
    events:
      - http:
          path: topdf
          method: post
          cors: true
  toPdf:
    handler: hander.pdfHandler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*